avg: avg_defines.vh avg_decode.sv avg.sv avg_test.sv
	vcs -sverilog -q -debug avg_decode.sv avg.sv avg_test.sv

clean: 
	rm -rf simv
	rm -rf simv.daidir
	rm -rf csrc
	rm -rf ucli.key
	rm -rf simv.vdb
	rm -rf DVEfiles 
	rm -rf inter.vdp
